[package]
name = "winsight"
version = "0.1.0"
authors = ["honerop <vi900@proton.me>"]
repository = "https://github.com/honerop/winsight"
homepage = "https://github.com/honerop/winsight"
readme = "README.md"
keywords = ["time-tracking", "productivity", "window", "cli"]
categories = ["command-line-utilities"]
edition = "2021"
description = "Window time tracker"
license = "MIT"

[dependencies]

# Only pulled in (and only compiled) when building for Linux.
[target.'cfg(target_os = "linux")'.dependencies]
swayipc = "3"      # for the Sway backend
x11rb = "0.13"     # for the X11 backend

# Only pulled in when building for macOS.
[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.5"
block2 = "0.5"
objc2-app-kit = { version = "0.2", features = [
    "NSWorkspace",
    "NSRunningApplication",
] }
objc2-foundation = "0.2"

# Only pulled in when building for Windows.
[target.'cfg(target_os = "windows")'.dependencies]
 windows = { version = "0.58", features = ["Win32_UI_WindowsAndMessaging", "Win32_UI_Accessibility", "Win32_System_Threading"] }
